page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

price_comparison_gp3/urls.py
from django.contrib import admin
from django.urls import path, include

from products.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', LandingPage.as_view(), name="landing_page"),

    # apps
    path('', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('contact/', include('contact.urls')),
    path('page/', include('page.urls')),

]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    # path('index', views.index, name='index'),
    # Products
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('modal/<int:pk>/', views.ProductModalView.as_view(), name='product_modal'),

    # Comments
    path('add_comment/<int:product_id>', views.add_comment, name='add_comment'),
    path('edit_comment/<int:comment_id>', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'),

    path('product_comments/<int:pk>', views.ProductComments.as_view(), name='product_comments'),

    # Likes
    path('like/', views.like_button, name='like'),

    # Add and Delete Product
    path('add_product/', views.add_product_view, name='add_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    ]

comment/models.py
from django.db import models
from datetime   import datetime

# Create your models here.
class Comment(models.Model):
    post = models.ForeignKey('comment', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=datetime.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

products/models.py
# Framework for Price Comparison tool
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Product(models.Model):
    product_name = models.CharField(max_length=512, blank=True, null=True)
    image = models.URLField(blank=True, null=True)
    amazon_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ebay_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    amazon_url = models.URLField(blank=True, null=True, default=None)
    ebay_url = models.URLField(blank=True, null=True, default=None)
    amazon_asin = models.CharField(max_length=12, blank=True, null=True, default=None)
    category = models.CharField(max_length=200, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True)
    features = models.TextField(blank=True, null=True)
    miscellaneous = models.CharField(max_length=3000, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name


class LikeButton(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    user = models.ManyToManyField(User, blank=True, related_name='likebutton')

    # content = models.TextField(null=True)

    def __str__(self):
        return f"{self.product.product_name} Likes"

    @property
    def total_likes(self):
        return self.user.count()


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, null=True, on_delete=models.PROTECT)
    content = models.TextField(max_length=3000)
    approved = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.BooleanField(default=False)
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Comments"
        ordering = ['-created']

    def __str__(self):
        return 'Comment on {} by {}'.format(self.product, self.user)

products/forms.py
from django import forms

from .models import Comment


class AddProductForm(forms.Form):
    """
    Adds products. Used with add product view and template
    """
    amazon_asin = forms.CharField(max_length=12)
    ebay_url = forms.CharField(max_length=200)


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Comment here!',
                'rows': 5,
                'cols': 50
                }))

    class Meta:
        model = Comment
        fields = ['content']

comment/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
import json
import environ

import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.views import generic

from test_files import ebay_products, amazon_products
from .forms import AddProductForm, CommentForm
from .models import Product, LikeButton, Comment

# Debug product fetching
env = environ.Env()
environ.Env.read_env()

# Debug product fetching
debug_gp = env.bool('DEBUG_GP')
amazon_responses = amazon_products.amazon_responses
ebay_responses = ebay_products.ebay_responses


class LandingPage(generic.ListView):
    template_name = 'products/index.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.order_by('product_name')[:10]


@login_required
def product_list(request, id):
    products = get_object_or_404(Product, id=id)
    return render(request, 'products.html', {'products': products})


# Show list of products
class ProductListView(generic.ListView):
    template_name = 'products/product_list.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.order_by('product_name')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ProductListView, self).get_context_data(**kwargs)
        # For displaying rows
        products = self.object_list
        count = products.count()
        iterations = int(count / 5)
        if count % 5 > 0:
            iterations += 1
        slices = []
        for i in range(iterations):
            slices.append(f"{i * 5}:{5 * (i + 1)}")
        context['slices'] = slices
        return context


# Show product details
class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['likes'] = LikeButton.objects.filter(product_id=pk).first()
        user = self.request.user
        if user.is_authenticated:
            context['user_like'] = LikeButton.objects.filter(user=self.request.user, product_id=pk)
        else:
            context['user_like'] = False

        # Split features into list of lines
        product = self.object
        features = product.description.splitlines()
        context['list_lines'] = features

        return context


# Show product modal
class ProductModalView(generic.DetailView):
    model = Product
    template_name = 'products/Modal.html'

    def get_context_data(self, **kwargs):
        context = super(ProductModalView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['likes'] = LikeButton.objects.filter(product_id=pk).first()
        context['comment_list'] = Comment.objects.filter(product=pk)
        user = self.request.user
        if user.is_authenticated:
            context['user_like'] = LikeButton.objects.filter(user=self.request.user, product_id=pk)
        else:
            context['user_like'] = False

        context['comment_list'] = Comment.objects.filter(product_id=pk)
        return context


# Like button
def like_button(request):
    if request.method == "POST":
        if request.POST.get("operation") == "like_submit" and request.is_ajax():
            likes_id = request.POST.get("likes_id", None)
            like_object = get_object_or_404(LikeButton, pk=likes_id)

            # Check if user already liked product
            if like_object.user.filter(id=request.user.id):
                # Remove user like from product
                like_object.user.remove(request.user)
                liked = False
            else:
                # Add user like to product
                like_object.user.add(request.user)
                liked = True

            # Create new context to feed back to AJAX call
            context = {"likes_count": like_object.total_likes,
                       "user_like"  : liked,
                       "likes_id"   : likes_id
                       }
            return HttpResponse(json.dumps(context), content_type='application/json')


def add_product_view(request):
    # Check if request was POST
    if request.method == 'POST':
        # Get amazon_asin & ebay_url
        amazon_asin = request.POST.get('amazon_asin')
        ebay_url = request.POST.get('ebay_url')

        # Get respective data
        amazon_product = get_amazon_product(amazon_asin)
        ebay_product = get_ebay_product(ebay_url)

        # Get or create product
        product, created = get_create_product(amazon_product, ebay_product)

        if product:
            if not created:
                messages.success(request, f"\"{product.product_name}\" has been updated")
            else:
                messages.success(request, f"\"{product.product_name}\" has been created")
        else:
            messages.error(request, f"Error: {created}")

    # Render page with any bound data and error messages
    context = {'form': AddProductForm(), 'product_list': Product.objects.order_by('id')}
    return render(request, 'products/add_product.html', context)


def delete_product(request, product_id):
    # Retrieve product
    product = get_object_or_404(Product, pk=product_id)
    product_name = product.product_name
    # Delete product
    product.delete()
    messages.success(request, f"\"{product_name}\" has been deleted")
    return redirect('products:add_product')


# Get amazon product from asin
def get_amazon_product(amazon_asin):
    url = env('AMAZON_URL')
    querystring = {"country": "US", "asin": amazon_asin}
    headers = {'x-rapidapi-key' : env('AMAZON_KEY'),
               'x-rapidapi-host': env('AMAZON_HOST')}

    if debug_gp:
        response = amazon_responses[int(amazon_asin)]
    else:
        response = requests.request("GET", url, headers=headers, params=querystring).json()

    amazon_context = {
        'asin'       : response['asin'],
        'price'      : response['prices']['current_price'],
        'description': response['description'],
        'features'   : response['features'],
        'image_urls' : response['images'],
        'url'        : response['full_link']
        }
    while None in amazon_context['features']:
        amazon_context['features'].remove(None)
    return amazon_context


# Get ebay product from url
def get_ebay_product(ebay_url):
    url = env('EBAY_URL')
    querystring = {"URL": ebay_url}
    headers = {'x-rapidapi-key' : env('EBAY_KEY'),
               'x-rapidapi-host': env('EBAY_HOST')}

    if debug_gp:
        response = ebay_responses[int(ebay_url)]
    else:
        response = requests.request("GET", url, headers=headers, params=querystring).json()

    ebay_context = {
        'name'      : response['title'],
        'price'     : response['prices']['current_price'],
        'url'       : response['full_link'],
        'image_urls': response['images'],
        'category'  : response['category'],
        }
    return ebay_context


# Get or crete product
def get_create_product(amazon_product, ebay_product):
    # Try to find a valid image url
    image_url = staticfiles_storage.url("/images/product_images/image_not_found.png")
    for image in amazon_product['image_urls'] + ebay_product['image_urls']:
        if image:
            image_url = image
            break

    # Create a product
    try:
        product, created = Product.objects.update_or_create(
                amazon_asin=amazon_product['asin'],
                defaults={'product_name': ebay_product['name'],
                          'description' : amazon_product['description'],
                          'amazon_price': amazon_product['price'],
                          'ebay_price'  : ebay_product['price'],
                          'amazon_url'  : amazon_product['url'],
                          'ebay_url'    : ebay_product['url'],
                          'category'    : ebay_product['category'],
                          'features'    : amazon_product['features'],
                          'image'       : image_url,
                          }
                )

        # Save product (to generate product pk)
        product.save()

        # Return product, created
        return product, created
    except ValidationError as e:
        return False, e
    except LookupError as e:
        return False, e


# Add comment to product
@login_required(login_url="signup")
def add_comment(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        user = request.user
        content = request.POST.get('content')
        comment = Comment(user=user, content=content, product=product, approved=True)
        comment.save()
        messages.success(request, 'Comment successfully added.')
    return redirect('products:product_modal', pk=product.pk)


# Delete comment
@login_required(login_url="signup")
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    product = get_object_or_404(Product, pk=comment.product.pk)
    comment.delete()
    messages.success(request, 'Comment successfully deleted.')
    return redirect('products:product_modal', pk=product.pk)


# Edit Comment
@login_required(login_url="signup")
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    form = CommentForm(instance=comment)

    if request.method == 'POST' and 'Update' in request.POST:
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)

products/templates/add_comment.html
Add Comment
<form action="{%url 'add_comment' product.pk %}" method="POST" id="submitform"}>
    {% csrf_token %}
    <br/>
    <textarea id="comment_body" name="comment_body" rows="4"
        cols="50">We appreciate your feedback!</textarea>
    <p><input type="submit" value="Submit Comment"></p>
</form>

products/templates/comment_list.html
{% extends 'products/product_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/item.css' %}">
<link rel="icon" href="{% static 'images/single_product_images/logo.png' %}" type="image/svg">
<link rel="icon" href="{% static 'images/single_product_images/logo.png' %}" type="image/svg">
<link rel="icon" href="{% static 'images/product_images/logo.png' %}" type="image/svg">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>Comments for {{ product|truncatechars:20 }}</title>
{% endblock css %}

{% block content %}
<div style="margin: 0 auto; width: 90%;">
    <h1>{{ product.product_name }}</h1>
    <strong>Amazon Price:</strong> ${{ product.amazon_price }}
    <br/><br/>
    <strong>E-Bay Price:</strong> ${{ product.ebay_price }}
    <br/><br/>
    <strong>Created:</strong> {{ product.created_at }}
    <br/><br/>
    <strong>Last Update:</strong> {{ product.updated_at }}
    <br/><br/>
    <hr>
    <br/>
    <strong>Add Comments</strong>
    {% if user.is_authenticated %}
    <form action="{% url 'products:add_comment' product.id %}" method="POST" id="submitform">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Submit Comment"></p>
    </form>
    {% else %}
    <div class="form_button">
        <input type="submit" value="Login!" onclick="window.location.href='{% url 'signup' %}'">
    </div>
    {% endif %}
    <br/>
    <hr>
    <br/>
    <strong> View All Comments</strong>
    <br/>
    <br/>
    <hr>

    {% for comment in product.comments.all %}
    <div class="comments">
        <div class="date">
            <strong>{{ comment.user }}</strong> | {{ comment.created }}
            {% if comment.updated %} | Last Updated: {{ comment.last_update }} {% endif %}
        </div>
        <a href="{% url 'products:edit_comment' comment.id %}">Edit</a>
        &nbsp;|&nbsp;
        <a href="{% url 'products:delete_comment' comment.id %}">Delete</a>
        <br/>
        <br/>
        {{ comment.content|linebreaks }}<br><br/>
        <hr>
        {% empty %}
        {% endfor %}
        <hr>
        <br/>
        <a href="{% url 'products:product_detail' product.id %}">Back to Product Detail</a>
        <br/><br/><br/>
        <a href="{% url 'products:product_modal' product.id %}">Back to Product Modal</a>
        <br/><br/><br/>
        <a href="{% url 'products:product_list' %}">Back to Product List</a>
        <br/><br/><br/>
    </div>
</div>
<footer></footer>

{% endblock content %}

products/templates/comments.html
<div class="comments"><br/>
    <hr>
    <br/>
    <h2>Comments: {{ product.comments.count }}</h2>
    <br/>
    <hr>

    <div>
        {% for comment in product.comments.all %}
        <div class="date">
            <strong>{{ comment.user }}</strong> | {{ comment.created }}
            {% if comment.updated %} | Edited: {{ comment.last_update }} {% endif %}
        </div>
        {% if comment.user == user %}
        <a href="{% url 'products:edit_comment' comment.id %}">Edit</a>
        &nbsp;|&nbsp;
        <a href="{% url 'products:delete_comment' comment.id %}">Delete</a>
        {% endif %}
        <br/>
        <br/>
        {{ comment.content|linebreaksbr }}<br><br/>
        <hr>
        {% empty %}
        <h2>Be the first to leave a comment!</h2>
        {% endfor %}
        <hr>
        <br/>
        <a href="{% url 'products:product_detail' product.id %}">To Product Detail</a>
        <br/><br/>
        <a href="{% url 'products:product_list' %}">To Product List</a>
        <br/><br/><br/>
    </div>
</div>

products/templates/deletecomment.html
<div class="main">
    <!-- Create a Form -->
    <h1> Delete Comment</h1>
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="javascript:history.go(-1)">Back to Product Detail</a>
        
        
    </form>
</div>

products/templates/edit_comment.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Comment</title>
    <link rel="icon" href="{% static 'images/register_images/PricedOut___1_-removebg-preview2.png' %}" type="image/svg">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
<body>
<header class="header1">
    {% include 'products/navlinks.html' %}
</header>
{% if messages %}
<div class="messages" style="text-align: center;">
    {% for message in messages %}
    <p {% if message.tags %} class="{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></p>
    {% endfor %}
</div>
{% endif %}
<br/>
<br/>
<div style="margin: 0 auto; width: 90%;">
    <h1>Edit Comment</h1>
    <form method="POST" action="{% url 'products:edit_comment' comment.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <br/>
        <input type="submit" value="Submit Update" name="Update">
        <br/><br/><br/>
        <input type="submit" value="Cancel" name="Cancel">
    </form>
</div>
<footer></footer>
</body>
</html>

products/templates/edit_comments.html
<h1>Edit Comment</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p  }}
    
    <input type="submit" value="Submit"></button>
    <a href = "{% url 'product_detail' pk }"> </a><input type="submit" value="Cancel"></button>

</form> 

products/templates/product_detail.html
<h1> Product Page</h1>

<!DOCTYPE html>
<html>
<body>
    
    <br><strong>  {{ products.product_name }}</strong><br/>
    {{ products.image }}<br/>
    Amazon Price $ {{ products.amazon_price }}<br/>
    E-Bay Price $ {{ products.ebay_price }}<br/>
    {{ products.description }}<br/>
    {{ products.miscellaneous }}<br/>
    Rating:{{ products.rating }}<br/>
    <strong> Created:</strong>{{ products.created_at }}<br/>
    <strong>Last Update:</strong>{{ products.updated_at }}<br/>
    <hr>
    <strong>Add Comments</strong>
    <form action="{%url 'add_comment' products.id %}" method="POST" id="submitform">
    {% csrf_token %}
    <br/>
    <textarea id="comment_body" name="comment_body" rows="4"
        cols="50">We appreciate your feedback!</textarea>
    <p><input type="submit" value="Submit Comment"></p>
</form>
<strong> View All Comments</strong>
    <br/>
    <hr>
    
    {% for comments in products.comments.all %}
    
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comments">
        <div class="date">
            
            {% if not comments.approved_comment %}
                <a class="btn btn-default" href="{% url 'product_detail' pk=products.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                
            {% endif %}
        </div>
        
    {{ comments.content }}<br>
    <br/><strong>{{ comments.user }}</strong>
    {{ comments.last_update }} <br/><a href="{% url 'edit_comments' products.pk comments.id %}" method="POST" id="submitform">Edit Comment </a>  <br/>
     <a href="{% url 'deletecomment'  products.pk comments.id %}" method="POST" id="submitform">Delete Comment </a> 
    <br/> <br/>

    
    <hr>
    <br/>

    
    {% endif %}
    {% empty %}
    {% endfor %}
    
    <a href="{% url 'products' %}">Back to Products</a>

 

        
   



    
<br/><br/><br/>
</body>
</html>