accounts/urls.py
from django.urls import path

from . import views
from .views import *

urlpatterns = [
    # path('', home, name="home"),
    path('register', views.register_attempt, name="register_attempt"),
    path('login', views.login_attempt, name="login_attempt"),
    path('logout', logout_user, name="logout"),
    path('token', token_send, name="token_send"),
    path('reset_success', reset_success, name="reset_success"),
    path('success', success, name='success'),
    path('verify/<auth_token>', verify, name="verify"),
    path('error', error_page, name="error"),
    path('faq', faq, name="faq"),
    path('about_us', about_us, name="about_us"),
    path('contact_us', contact_us, name="contact_us"),
    path('resetting/<reset_token>', resetting, name="resetting"),
    path('passwordreset', reset_attempt, name="reset_attempt"),
    path('resetpage', resetpage, name="resetpage"),
    path('signup/', views.signup, name="signup"),
    ]

contact/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("contact", views.contact, name="contact"),
    path('save_message', views.save_message, name="save_message"),
    ]

page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

price_comparison_gp3/urls.py
from django.contrib import admin
from django.urls import path, include

from products.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', LandingPage.as_view(), name="landing_page"),

    # apps
    path('', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('contact/', include('contact.urls')),
    path('page/', include('page.urls')),

]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    # path('index', views.index, name='index'),
    # Products
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('modal/<int:pk>/', views.ProductModalView.as_view(), name='product_modal'),

    # Comments
    path('add_comment/<int:product_id>', views.add_comment, name='add_comment'),
    path('edit_comment/<int:comment_id>', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'),

    path('product_comments/<int:pk>', views.ProductComments.as_view(), name='product_comments'),

    # Likes
    path('like/', views.like_button, name='like'),

    # Add and Delete Product
    path('add_product/', views.add_product_view, name='add_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    ]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=100, blank=True, default="")
    reset_token = models.CharField(max_length=100, blank=True, default="")
    is_verified = models.BooleanField(default=False)
    is_reset = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

contact/models.py
from django.db import models


class Message(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"From {self.name} sent {self.created}"

contact/forms.py
from django import forms

from .models import Message


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

accounts/views.py
import uuid
import environ

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import redirect, render

from .models import *

# Enable or disable email
env = environ.Env(
        # set casting, default value
        SEND_EMAIL=(bool, False)
        )
environ.Env.read_env()

# Send email or instant verification
send_email = env.bool('SEND_EMAIL')


@login_required
def home(request):
    return redirect('products:product_list')


def login_attempt(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user_obj = User.objects.filter(email=email).first()
        if user_obj is None:
            messages.success(request, 'User not found.')
            return redirect('signup')

        profile_obj = Profile.objects.filter(user=user_obj).first()

        if not profile_obj.is_verified:
            messages.success(request, 'Profile is not verified check your mail.')
            return redirect('signup')

        user = authenticate(username=user_obj.username, password=password)
        if user is None:
            messages.success(request, 'Wrong password.')
            return redirect('signup')

        login(request, user)
        return redirect('products:product_list')

    return render(request, 'signup.html')


def register_attempt(request):
    if request.method == 'POST':
        firstname = request.POST.get('first-name')
        lastname = request.POST.get('last-name')
        email = request.POST.get('email')
        phonenumber = request.POST.get('Number')
        password = request.POST.get('password')

        try:
            if User.objects.filter(email=email).first():
                messages.success(request, 'Email is taken.')
                return redirect('signup')

            user_obj = User(username=email, email=email, first_name=firstname, last_name=lastname)
            user_obj.set_password(password)
            user_obj.save()

            if send_email:
                current_site = get_current_site(request)
                auth_token = str(uuid.uuid4())
                profile_obj = Profile.objects.create(user=user_obj, auth_token=auth_token)
                profile_obj.save()
                send_mail_after_registration(email, auth_token, current_site)
                return redirect('token_send')
            else:
                profile_obj = Profile.objects.create(user=user_obj)
                profile_obj.is_verified = True
                profile_obj.auth_token = ""
                profile_obj.save()
                login(request, user_obj)
                return redirect('products:product_list')

        except Exception as e:
            print(e)
            return redirect("landing_page")

    return render(request, 'signup.html')


def success(request):
    return render(request, 'success.html')


def token_send(request):
    return render(request, 'token_send.html')


def reset_success(request):
    return render(request, 'reset_success.html')


def verify(request, auth_token):
    try:
        profile_obj = Profile.objects.filter(auth_token=auth_token).first()

        if profile_obj:
            if profile_obj.is_verified:
                messages.success(request, 'Your account is already verified.')
                return redirect('signup')
            profile_obj.is_verified = True
            profile_obj.auth_token = ""
            profile_obj.save()
            messages.success(request, 'Your account has been verified.')
            return redirect('signup')
        else:
            return redirect('signup')
    except Exception as e:
        print(e)
        return redirect('')


def error_page(request):
    return render(request, 'error.html')


def resetting(request, reset_token):
    try:
        profile_obj = Profile.objects.filter(reset_token=reset_token).first()

        if profile_obj:
            if profile_obj.is_reset:
                messages.success(request, 'You have already used this link to reset your password.')
                return redirect('reset_attempt')
            # profile_obj.is_reset = True
            profile_obj.save()
            messages.success(request, 'You will now be able to reset your password.')
            return redirect('resetpage')
        else:
            return redirect('error')
    except Exception as e:
        print(e)
        return redirect('home')


def send_mail_after_registration(email, token, site):
    subject = 'Your accounts need to be verified'
    message = f'Hi paste the link to verify your account:\n{site}/verify/{token}'
    email_from = 'PricedOut@PricedOut.com'  # settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject, message, email_from, recipient_list)


def faq(request):
    return render(request, 'faq.html')


def about_us(request):
    return render(request, 'About.html')


def contact_us(request):
    return render(request, 'Contact.html')


def send_mail_password_reset(email, token, site):
    subject = 'Reset your password'
    message = f'Hi paste the link to reset your password:\n{site}/resetting/{token}'
    email_from = 'PricedOut@PricedOut.com'  # settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject, message, email_from, recipient_list)


def reset_attempt(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        try:
            user = User.objects.filter(email=email).first()
            if user:
                current_site = get_current_site(request)
                reset_token = str(uuid.uuid4())
                profile_obj = Profile.objects.get(user=user)
                profile_obj.reset_token = reset_token
                profile_obj.save()
                send_mail_password_reset(email, reset_token, current_site)
                return redirect('token_send')

            else:
                messages.success(request, 'Email not associated with an account.')
                return redirect('reset_attempt')

        except Exception as e:
            print(e)

    return render(request, 'passwordreset.html')


# user id and the token, check if it is the user id and the correct token


def resetpage(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        print(email, password)

        user_obj = User.objects.filter(email=email).first()

        if user_obj is None:
            messages.success(request, 'User not found.')
            return redirect('signup')

        profile_obj = Profile.objects.filter(user=user_obj).first()

        if not profile_obj.is_reset:
            user_obj.set_password(password)
            user_obj.save()
            profile_obj.reset_token = ""
            profile_obj.save()
            return redirect('reset_success')

        if profile_obj.is_reset:
            messages.success(request, 'Please click the link emailed to you with a token.')
            return redirect('resetpage')

    return render(request, 'resetpage.html')


def signup(request):
    return render(request, 'signup.html')


def logout_user(request):
    logout(request)
    return render(request, 'signup.html')

contact/views.py
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import ContactForm
from .models import Message


# Create your views here.
def homepage(request):
    return render(request, "main/home.html")


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body = {
                'first_name': form.cleaned_data['first_name'],
                'last_name' : form.cleaned_data['last_name'],
                'email'     : form.cleaned_data['email_address'],
                'message'   : form.cleaned_data['message'],
                }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'admin@example.com', ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect("main:homepage")

    form = ContactForm()
    return render(request, "main/contact.html", {'form': form})


def save_message(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        Message.objects.create(name=name, email=email, message=message)
        messages.success(request, "Thank you for contacting us! We will respond within 1-2 business days.")
    return redirect('contact_us')

accounts/templates/About.html
{% extends 'products/product_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
<link rel="icon" href="{% static 'images/landingpage-images/Pricedout2.svg' %}" type="image/svg">
<title>PricedOut | About Us</title>
{% endblock css %}

{% block pattern_div %}
<body>
    <header>
        {% include 'products/navlinks.html' %}
    </header>
{% endblock pattern_div %}

{% block content %}
    <main>
        <div class="stripes">
            <img src="{% static 'images/landingpage-images/long.svg' %}" alt="stripes">
            <img src="{% static 'images/landingpage-images/medium.svg' %}" alt="stripes">
            <img src="{% static 'images/landingpage-images/short.svg' %}" alt="stripes">
            <img src="{% static 'images/aboutpage-images/extraline.svg' %}" alt="stripes">
        </div>

       <div class="text1"> 
            <div class="solo">
                <img src="{% static 'images/aboutpage-images/solo.svg' %}" alt="solo" class="solo">
            </div>  
            <div class="about">
                    <h1>
                        <span class="bold"> About </span> Us
                    </h1>

                    <div class="p1">
                        <p>
                                Priced Out serves as a web platform connecting smart and savvy shoppers <br>
                                with the products they enjoy, at competitive prices.
                        </p>
                     </div>
                     <div class="p2">
                        <p>
                                We're ensuring our members can easily view and compare some of the best <br>
                                products on the market on two of the world's largest ecommerce websites - <br>
                                Amazon and E-bay. 
                        </p>
                     </div>
                     <div class="p3">
                        <p>
                                We understand the importance of our member's buying decisions, and we <br>
                                provide a space to discover products they love, share them with a friend or <br>
                                family and find value in the goods they invest in.
                        </p>
                     </div>
            </div>
        </div>

       <div class="text2">
           <div class="duo">
                <img src="{% static 'images/aboutpage-images/duo.svg' %}" alt="duo" class="duo">
           </div> 
            <div class="how">
                    <h1>
                        <span class="bold"> How</span> to Use
                    </h1>
                <div class="sign">
                    <img src="{% static 'images/aboutpage-images/pen.svg' %}" alt="pen">
                    <p>
                    1. <span class="bold">Sign-up</span>
                        on our Priced out homepage by clicking on the get <br>
                        started button. Or, if you'd like to search for products on <br>
                        the fly, click on a product tile on the homepage. <br>
                    </p>
                </div>
                <div class="compare">
                    <img src="{% static 'images/aboutpage-images/tag.svg' %}" alt="tag">
                    <p>
                    2.  <span class="bold">Compare</span>
                        the price and details of products you care about <br>
                        across Amazon and E-bay. <br>
                    </p>
                </div>
                <div class="comment">
                    <img src="{% static 'images/aboutpage-images/thumbs.svg' %}" alt="thumbs">
                    <p>
                    3. <span class="bold">Comment</span>,
                        like, and share the products you're considering on <br>
                        your personal social media platforms to connect with family <br>
                        or friends.
                    </p>
                </div>
            </div>
        </div>
    </main>

    <footer>
    </footer>
{% endblock content %}

accounts/templates/Contact.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <link rel="icon" href="{% static 'images/contact-images/PricedOut___1_-removebg-preview2.png' %}" type="image/svg">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
</head>
<body>
<header class="header1">
    {% include 'products/navlinks.html' %}
</header>
<div class="messages" style="text-align: center;">
    {% for message in messages %}
    <p {% if message.tags %} class="{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></p>
    {% endfor %}
</div>
<Section class="Main">
    <div class="touch"><h4>Get In Touch</h4></div>
    <div class="main-content">
        <div class="card">
            <form class="form" action="{% url 'save_message' %}" method="POST">
                {% csrf_token %}
                <h5>Leave us a message</h5>
                <div class="floating">
                    <input id="name" class="floating_input" name="name" type="text" placeholder="Name" required>
                    <label for="name" class="floating_label" data-content="Name"> <span class="hidden"> Name </span></label>
                </div>

                <div class="floating">
                    <input id="email" class="floating_input" name="email" type="email" placeholder="Email Address" required>
                    <label for="email" class="floating_label" data-content="Email"> <span class="hidden"> Email Address </span></label>
                </div>

                <div class="floating" id="float">
                    <input id="message" class="floating_input" name="message" type="text" placeholder=" Your Message" required>
                    <label for="message" class="floating_label" data-content="message"> <span class="hidden"> Your Message </span></label>
                </div>

                <input class="send-btn" type="submit" value="Submit">
            </form>
        </div>
        <div class="address">
            <p>5439 Land of Milk & Honey Blvd
                <span>Suite 112</span>
                <span>Atlanta, GA 30303 </span> <br>
                <span class="contact"> 1(219) 867-5309</span><br><br>
                <span class="contact">CustomerHelp@RandomShop.com</span>
            </p>
            <img src="{% static 'images/contact-images/Rectangle19.svg' %}" alt="">
        </div>
    </div>
</Section>

<footer>
    <div class="ft">
        <div class="qlinks ">
            <ul>
                <dl>Quick Links</dl>
                <li><a href="{% url 'signup' %}">Register</a></li>
                <li><a href="{% url 'signup' %}">Login</a></li>
            </ul>
        </div>

        <div class="others">
            <ul>
                <dl>Others</dl>
                <li><a href="{% url 'faq' %}">User FAQs</a></li>
                <li><a href="{% url 'contact_us' %}">Contact Us</a></li>
                <li><a href="#">Legal</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms and Conditions</a></li>
            </ul>
        </div>

        <div class="products">
            <ul>
                <dl>Products</dl>
                <li><a href="{% url 'products:add_product' %}">Review</a></li>
                <li><a href="{% url 'products:product_list' %}">Compare</a></li>
                <li><a href="#">Buy</a></li>
            </ul>
        </div>

        <div class="subscribe">
            <p>Subscribe to our newsletter and be the first to <span>know about our updates </span></p>
            <div class="sub">
                <div class="email">
                    <input id="input_email1" class="floating_input1" name="email Address" type="email"
                           placeholder="Email Address">
                </div>
                <button>Subscribe</button>
            </div>

        </div>

    </div>
    <div class="copyright">
        <p>Copyright 2020. All rights reserved</p>
        <i class="fab fa-youtube"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-twitter"></i>
    </div>

</footer>
</body>
</html>

accounts/templates/Signup.html
{% extends 'products/product_base.html' %}
{% load static %}
{% block css %}
<link rel="icon" href="{% static '/images/register_images/PricedOut___1_-removebg-preview 2.png' %}" type="image/svg">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"/>
<link rel="stylesheet" href="{% static 'css/Signup.css' %}">
<title>PricedOut | Signup</title>
{% endblock css %}

{% block pattern_div %}
<body>
<header class="header1">
    {% include 'products/navlinks.html' %}
</header>
{% endblock pattern_div %}

{% block content %}
<Section class="Main">

    <div class="main-content">
        <div class="card">
            <div class="rg"><h1>Register Here</h1></div>
            <Div class="form">
                <form action="{% url 'register_attempt' %}" method="post">
                    {% csrf_token %}
                    <div class="floating1">
                        <div class="flt">
                            <input id="input_fname" class="floating_input" name="first-name" type="text"
                                   placeholder="First Name">
                            <label for="input_fname" class="floating_label" data-content="First Name">
                                <span class="hidden"> First Name </span>
                            </label>
                        </div>
                        <div class="ltn">
                            <input id="input_lname" class="floating_input" name="last-name" type="text"
                                   placeholder="Last Name">
                            <label for="input_lname" class="floating_label" data-content="Last Name">
                                <span class="hidden"> Last Name </span>
                            </label>
                        </div>
                    </div>

                    <div class="floating">
                        <input id="input_email" class="floating_input" name="email" type="email" placeholder="Email">
                        <label for="input_email" class="floating_label" data-content="Email">
                            <span class="hidden"> Email </span>
                        </label>
                    </div>

                    <div class="floating" id="float">
                        <input id="input_number" class="floating_input" name="Number" type="number"
                               placeholder="Phone Number">
                        <label for="input_number" class="floating_label" data-content="Phone Number">
                            <span class="hidden"> Phone Number </span>
                        </label>
                    </div>

                    <div class="floating">
                        <input id="input_password" class="floating_input" name="password" type="password"
                               placeholder="Password">
                        <label for="input_password" class="floating_label password" data-content="Password">
                            <span class="hidden"> Password </span>
                        </label>
                        <span><input type="checkbox" onclick="myFunction()">Show Password</span>
                    </div>
                    <script>
                        function myFunction() {
                          var x = document.getElementById("input_password");
                          if (x.type === "password") {
                            x.type = "text";
                          } else {
                            x.type = "password";
                          }
                        }
                    </script>
                    <p> By creating an account you agree to our <a class="terms" href="#">User Agreement</a> and
                        acknowledge reading our
                        <span> <a class="terms" href="#">User Privacy Notice</a>.</span>
                    </p>
                    <input type="submit" class="create" value="Create Accounts">
                </form>
            </Div>
        </div>
        <div class="social">

            <div class="lg"><h1>Login</h1></div>
            <div class="social-buttons">
                <button class="google">
                    <img class="ggle" src="https://img.icons8.com/color/48/000000/google-logo.png"/>Login with Google
                </button>
                <button class="facebook">
                    <img class="fb" src="https://img.icons8.com/color/48/000000/facebook.png"/>Login with Facebook
                </button>
                <button class="Apple">
                    <img class="appl" src="https://img.icons8.com/ios-filled/50/000000/mac-os.png"/>Login with Apple
                </button>
            </div>
            <div class="lg-email"><h5>or login with Email</h5></div>
            <div class="login-form">
                <form action="{% url 'login_attempt' %}" method="post">
                    {% csrf_token %}
                    <input id="email" name="email" class="login-input" type="email" placeholder="Email">
                    <input id="password" name="password" class="login-input" type="Password" placeholder="Password">

                    <input id="checkbox" type="checkbox">
                    <label class="remember" for="checkbox"> Remember Me</label>
                    <br/>
                    <a class="forget-pass" href="{% url 'reset_attempt' %}"> Forget Password</a>

                    <input class="login-btn" type="submit" value="Login">
                </form>

            </div>
        </div>
    </div>
</Section>
{% endblock content %}

accounts/templates/error.html
{% extends "base.html"%}

    {% block content %}


    <div class="global-container">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Error</h3>

            <a href="/" class="btn btn-success">Back</a>
            
            </div>
        </div>
    </div>
    </div>
    

    {% endblock %}

accounts/templates/home.html
{% extends "base.html"%}

    {% block content %}


    <div class="global-container">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Welcome</h3>
          
            </div>
        </div>
    </div>
    </div>
    

    {% endblock %}

accounts/templates/thank_you.html
{% extends 'products/product_base.html' %}
{% load static %}
{% block css %}
<link rel="icon" href="{% static 'images/contact-images/PricedOut___1_-removebg-preview2.png' %}" type="image/svg">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"/>
<link rel="stylesheet" href="{% static 'css/contact.css' %}">
<title>PricedOut | Contact Us</title>
{% endblock css %}
{% block pattern_div %}
<body>
<header>
    <div class="logo-div"></div>
    {% include 'products/navlinks.html' %}
</header>
{% endblock pattern_div %}
{% block content %}
<Section class="Main">
    <div class="touch"><h4>Get In Touch</h4></div>
    <div class="main-content">
        <div class="card">
            <p>Thank you for your message!</p>
        </div>
        <div class="address">
            <p>5439 Land of Milk & Honey Blvd
                <span>Suite 112</span>
                <span>Atlanta, GA 30303 </span> <br>
                <span class="contact"> 1(219) 867-5309</span><br><br>
                <span class="contact">CustomerHelp@RandomShop.com</span>
            </p>
            <img src="{% static 'images/contact-images/Rectangle19.svg' %}" alt="">
        </div>
    </div>
</Section>

<footer>
    <div class="ft">
        <div class="qlinks ">
            <ul>
                <dl>Quick Links</dl>
                <li><a href="{% url 'signup' %}">Register</a></li>
                <li><a href="{% url 'signup' %}">Login</a></li>
            </ul>
        </div>

        <div class="others">
            <ul>
                <dl>Others</dl>
                <li><a href="{% url 'faq' %}">User FAQs</a></li>
                <li><a href="{% url 'contact_us' %}">Contact Us</a></li>
                <li><a href="#">Legal</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms and Conditions</a></li>
            </ul>
        </div>

        <div class="products">
            <ul>
                <dl>Products</dl>
                <li><a href="{% url 'products:add_product' %}">Review</a></li>
                <li><a href="{% url 'products:product_list' %}">Compare</a></li>
                <li><a href="#">Buy</a></li>
            </ul>
        </div>

        <div class="subscribe">
            <p>Subcribe to our newsletter and be the first to <span>know about our updates </span></p>
            <div class="sub">
                <div class="email">
                    <input id="input_email1" class="floating_input1" name="email Address" type="email"
                           placeholder="Email Address">
                </div>
                <button>Subscribe</button>
            </div>

        </div>

    </div>
    <div class="copyright">
        <p>Copyright 2020. All rights reserved</p>
        <i class="fab fa-youtube"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-twitter"></i>
    </div>

</footer>
{% endblock content %}

accounts/templates/token_send.html
{% extends "base.html"%}

    {% block content %}


    
    <div class="global-container">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">We have sent an email to you </h3>
            <div class="card-text text-center">
                Please check your mail
            </div>
        </div>
    </div>
    </div>


    {% endblock %}