page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

price_comparison_gp3/urls.py
from django.contrib import admin
from django.urls import path, include

from products.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', LandingPage.as_view(), name="landing_page"),

    # apps
    path('', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('contact/', include('contact.urls')),
    path('page/', include('page.urls')),

]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    # path('index', views.index, name='index'),
    # Products
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('modal/<int:pk>/', views.ProductModalView.as_view(), name='product_modal'),

    # Comments
    path('add_comment/<int:product_id>', views.add_comment, name='add_comment'),
    path('edit_comment/<int:comment_id>', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'),

    path('product_comments/<int:pk>', views.ProductComments.as_view(), name='product_comments'),

    # Likes
    path('like/', views.like_button, name='like'),

    # Add and Delete Product
    path('add_product/', views.add_product_view, name='add_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    ]

products/models.py
# Framework for Price Comparison tool
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Product(models.Model):
    product_name = models.CharField(max_length=512, blank=True, null=True)
    image = models.URLField(blank=True, null=True)
    amazon_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ebay_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    amazon_url = models.URLField(blank=True, null=True, default=None)
    ebay_url = models.URLField(blank=True, null=True, default=None)
    amazon_asin = models.CharField(max_length=12, blank=True, null=True, default=None)
    category = models.CharField(max_length=200, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True)
    features = models.TextField(blank=True, null=True)
    miscellaneous = models.CharField(max_length=3000, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name


class LikeButton(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    user = models.ManyToManyField(User, blank=True, related_name='likebutton')

    # content = models.TextField(null=True)

    def __str__(self):
        return f"{self.product.product_name} Likes"

    @property
    def total_likes(self):
        return self.user.count()


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, null=True, on_delete=models.PROTECT)
    content = models.TextField(max_length=3000)
    approved = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.BooleanField(default=False)
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Comments"
        ordering = ['-created']

    def __str__(self):
        return 'Comment on {} by {}'.format(self.product, self.user)

products/forms.py
from django import forms

from .models import Comment


class AddProductForm(forms.Form):
    """
    Adds products. Used with add product view and template
    """
    amazon_asin = forms.CharField(max_length=12)
    ebay_url = forms.CharField(max_length=200)


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Comment here!',
                'rows': 5,
                'cols': 50
                }))

    class Meta:
        model = Comment
        fields = ['content']

products/views.py
import json
import environ

import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.views import generic

from test_files import ebay_products, amazon_products
from .forms import AddProductForm, CommentForm
from .models import Product, LikeButton, Comment

# Debug product fetching
env = environ.Env()
environ.Env.read_env()

# Debug product fetching
debug_gp = env.bool('DEBUG_GP')
amazon_responses = amazon_products.amazon_responses
ebay_responses = ebay_products.ebay_responses


class LandingPage(generic.ListView):
    template_name = 'products/index.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.order_by('product_name')[:10]


@login_required
def product_list(request, id):
    products = get_object_or_404(Product, id=id)
    return render(request, 'products.html', {'products': products})


# Show list of products
class ProductListView(generic.ListView):
    template_name = 'products/product_list.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.order_by('product_name')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ProductListView, self).get_context_data(**kwargs)
        # For displaying rows
        products = self.object_list
        count = products.count()
        iterations = int(count / 5)
        if count % 5 > 0:
            iterations += 1
        slices = []
        for i in range(iterations):
            slices.append(f"{i * 5}:{5 * (i + 1)}")
        context['slices'] = slices
        return context


# Show product details
class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['likes'] = LikeButton.objects.filter(product_id=pk).first()
        user = self.request.user
        if user.is_authenticated:
            context['user_like'] = LikeButton.objects.filter(user=self.request.user, product_id=pk)
        else:
            context['user_like'] = False

        # Split features into list of lines
        product = self.object
        features = product.description.splitlines()
        context['list_lines'] = features

        return context


# Show product modal
class ProductModalView(generic.DetailView):
    model = Product
    template_name = 'products/Modal.html'

    def get_context_data(self, **kwargs):
        context = super(ProductModalView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['likes'] = LikeButton.objects.filter(product_id=pk).first()
        context['comment_list'] = Comment.objects.filter(product=pk)
        user = self.request.user
        if user.is_authenticated:
            context['user_like'] = LikeButton.objects.filter(user=self.request.user, product_id=pk)
        else:
            context['user_like'] = False

        context['comment_list'] = Comment.objects.filter(product_id=pk)
        return context


# Like button
def like_button(request):
    if request.method == "POST":
        if request.POST.get("operation") == "like_submit" and request.is_ajax():
            likes_id = request.POST.get("likes_id", None)
            like_object = get_object_or_404(LikeButton, pk=likes_id)

            # Check if user already liked product
            if like_object.user.filter(id=request.user.id):
                # Remove user like from product
                like_object.user.remove(request.user)
                liked = False
            else:
                # Add user like to product
                like_object.user.add(request.user)
                liked = True

            # Create new context to feed back to AJAX call
            context = {"likes_count": like_object.total_likes,
                       "user_like"  : liked,
                       "likes_id"   : likes_id
                       }
            return HttpResponse(json.dumps(context), content_type='application/json')


def add_product_view(request):
    # Check if request was POST
    if request.method == 'POST':
        # Get amazon_asin & ebay_url
        amazon_asin = request.POST.get('amazon_asin')
        ebay_url = request.POST.get('ebay_url')

        # Get respective data
        amazon_product = get_amazon_product(amazon_asin)
        ebay_product = get_ebay_product(ebay_url)

        # Get or create product
        product, created = get_create_product(amazon_product, ebay_product)

        if product:
            if not created:
                messages.success(request, f"\"{product.product_name}\" has been updated")
            else:
                messages.success(request, f"\"{product.product_name}\" has been created")
        else:
            messages.error(request, f"Error: {created}")

    # Render page with any bound data and error messages
    context = {'form': AddProductForm(), 'product_list': Product.objects.order_by('id')}
    return render(request, 'products/add_product.html', context)


def delete_product(request, product_id):
    # Retrieve product
    product = get_object_or_404(Product, pk=product_id)
    product_name = product.product_name
    # Delete product
    product.delete()
    messages.success(request, f"\"{product_name}\" has been deleted")
    return redirect('products:add_product')


# Get amazon product from asin
def get_amazon_product(amazon_asin):
    url = env('AMAZON_URL')
    querystring = {"country": "US", "asin": amazon_asin}
    headers = {'x-rapidapi-key' : env('AMAZON_KEY'),
               'x-rapidapi-host': env('AMAZON_HOST')}

    if debug_gp:
        response = amazon_responses[int(amazon_asin)]
    else:
        response = requests.request("GET", url, headers=headers, params=querystring).json()

    amazon_context = {
        'asin'       : response['asin'],
        'price'      : response['prices']['current_price'],
        'description': response['description'],
        'features'   : response['features'],
        'image_urls' : response['images'],
        'url'        : response['full_link']
        }
    while None in amazon_context['features']:
        amazon_context['features'].remove(None)
    return amazon_context


# Get ebay product from url
def get_ebay_product(ebay_url):
    url = env('EBAY_URL')
    querystring = {"URL": ebay_url}
    headers = {'x-rapidapi-key' : env('EBAY_KEY'),
               'x-rapidapi-host': env('EBAY_HOST')}

    if debug_gp:
        response = ebay_responses[int(ebay_url)]
    else:
        response = requests.request("GET", url, headers=headers, params=querystring).json()

    ebay_context = {
        'name'      : response['title'],
        'price'     : response['prices']['current_price'],
        'url'       : response['full_link'],
        'image_urls': response['images'],
        'category'  : response['category'],
        }
    return ebay_context


# Get or crete product
def get_create_product(amazon_product, ebay_product):
    # Try to find a valid image url
    image_url = staticfiles_storage.url("/images/product_images/image_not_found.png")
    for image in amazon_product['image_urls'] + ebay_product['image_urls']:
        if image:
            image_url = image
            break

    # Create a product
    try:
        product, created = Product.objects.update_or_create(
                amazon_asin=amazon_product['asin'],
                defaults={'product_name': ebay_product['name'],
                          'description' : amazon_product['description'],
                          'amazon_price': amazon_product['price'],
                          'ebay_price'  : ebay_product['price'],
                          'amazon_url'  : amazon_product['url'],
                          'ebay_url'    : ebay_product['url'],
                          'category'    : ebay_product['category'],
                          'features'    : amazon_product['features'],
                          'image'       : image_url,
                          }
                )

        # Save product (to generate product pk)
        product.save()

        # Return product, created
        return product, created
    except ValidationError as e:
        return False, e
    except LookupError as e:
        return False, e


# Add comment to product
@login_required(login_url="signup")
def add_comment(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        user = request.user
        content = request.POST.get('content')
        comment = Comment(user=user, content=content, product=product, approved=True)
        comment.save()
        messages.success(request, 'Comment successfully added.')
    return redirect('products:product_modal', pk=product.pk)


# Delete comment
@login_required(login_url="signup")
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    product = get_object_or_404(Product, pk=comment.product.pk)
    comment.delete()
    messages.success(request, 'Comment successfully deleted.')
    return redirect('products:product_modal', pk=product.pk)


# Edit Comment
@login_required(login_url="signup")
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    form = CommentForm(instance=comment)

    if request.method == 'POST' and 'Update' in request.POST:
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)

products/templates/products/Modal.html
{% extends 'products/product_base.html' %}
{% load static %}
{% block css %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
<link href="{% static 'css/modal.css' %}" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Average+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="icon" href="{% static 'images/modal-images/brandlogo.png' %}" type="image/svg">
<title>PricedOut | {{ product|truncatechars:20 }} Summary</title>
{% endblock css %}

{% block pattern_div %}
<body>
<div class="container">

    <header>
        <div class="logo">
            <img src="{% static 'images/modal-images/brandlogo.png' %}" alt="priced-out-brand-logo">
        </div>
        {% include 'products/navlinks.html' %}
    </header>
    {% endblock pattern_div %}

    {% block content %}
    <h1>Product Summary</h1>
    <img src="{% static 'images/modal-images/boxes.png' %}" alt="3-decorative-golden-squares-randomly-overlapping"
         class="boxes">

    <div class="main">
        <div class="product">
            <a href="{% url 'products:product_detail' product.pk %}" title="{{ product }}">
                <figure>
                    <img src="{{ product.image }}" alt="{{ product.image|truncatechars:20 }}">
                    <figcaption>
                        {{ product }}
                    </figcaption>
                </figure>
            </a>
        </div>

        <div class="info">
            <p>Product</p>
            <p>Price</p>
            <p>Category</p>
            <p></p>
        </div>
        <div class="amazon">
            <h2>Amazon</h2>
            <p title="{{ product }}">{{ product|truncatechars:16 }}</p>
            <p><a href="{{ product.amazon_url }}">{{ product.amazon_price }}</a></p>
            <p>{{ product.category }}</p>
            <p></p>
        </div>
        <div class="ebay">
            <h2>Ebay</h2>
            <p title="{{ product }}">{{ product|truncatechars:16 }}</p>
            <p><a href="{{ product.ebay_url }}">{{ product.ebay_price }}</a></p>
            <p>{{ product.category }}</p>
            <p></p>
        </div>
    </div>

    <div class="footer">
        <div class="footer-top">
            <div class="capsule">
                {% if user.is_authenticated %}
                <a id="{{ likes.id }}" class="like_icon"
                   style="color: {% if user_like %} orange {% else %} lightgrey {% endif %};">
                    <i class="fa fa-thumbs-o-up fa-flip-horizontal"></i>
                </a>
                {% endif %}
                <p>Likes <a id="likes_count">{{ likes.total_likes }}</a></p>
            </div>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            {% include 'products/like_button_script.html' %}

            <div class="social-icons">
                <a href="https://www.facebook.com/"><img src="{% static 'images/modal-images/fb-icon.svg' %}"></a>
                <a href="https://twitter.com/"><img src="{% static 'images/modal-images/twtr-icon.svg' %}"></a>
                <a href="https://www.instagram.com/"><img src="{% static 'images/modal-images/ig-icon.svg' %}"></a>
                <!--<a href="#"><img src="{% static 'images/modal-images/link-icon.svg' %}" class="link"></a>-->
                <input type="image" src="{% static 'images/modal-images/submit.svg' %}" class="link"
                       alt="Submit Comment" title="Submit Comment" form="submitform">
                <!--<p><input type="submit" value="Submit" form="submitform"></p>-->
            </div>
        </div>
        <form action="{% url 'products:add_comment' product.id %}" method="POST" id="submitform">
            {% csrf_token %}
            <textarea rows="15" cols="120" id="content" name="content" placeholder="Leave a comment!"
                      required></textarea>
        </form>
    </div>
    <div class="blue-border"></div>
</div>
{% include 'comments.html' %}
{% endblock content %}

products/templates/products/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/item.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static 'images/product_images/logo.png' %}" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/single_product_images/logo.png' %}" type="image/png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Add/Delete Products</title>
</head>
<body>

<header>
    <div class="headerGradient">
        {% include 'products/navlinks.html' %}
    </div>
</header>

{% if messages %}
<div class="messages" style="text-align: center;">
    {% for message in messages %}
    <p {% if message.tags %} class="{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></p>
    {% endfor %}
</div>
{% endif %}

<div class="productName">
    <h1>Add a Product</h1>
</div>
<div style="text-align: center;">
    <form action="{% url 'products:add_product' %}" method="POST">
        {% csrf_token %}
        <h3>{{ form.amazon_asin.label }}</h3>
        {{ form.amazon_asin }}
        {{ form.amazon_asin.errors.as_text|escape }}
        <br/><br/>

        <h3>{{ form.ebay_url.label }}</h3>
        {{ form.ebay_url }}
        {{ form.ebay_url.errors.as_text|escape }}

        <p><input type="submit" value="Add Product"></p>
    </form>
</div>
<br/>
<br/>
<div class="productName">
    <h1>Delete Products</h1>
</div>
<table style="margin: 0 auto;">
    {% for product in product_list %}
    <tr>
        <td style="padding: 20px; width: 100px;">ID {{ product.id }}</td>
        <td style="width: 50px;"><a href="{% url 'products:delete_product' product.id %}">
            <i class="fa fa-trash"></i></a></td>
        <td><a href="{% url 'products:product_detail' product.id %}" title="{{ product }}">
            {{ product|truncatechars:60 }}</a></td>
    </tr>
    {% endfor %}
</table>
<footer></footer>
</body>
</html>

products/templates/products/index.html
{% extends 'products/product_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="icon" href="{% static 'images/landingpage-images/Pricedout1.svg' %}" type="image/svg">
<title>PricedOut</title>
{% endblock css %}

{% block pattern_div %}
<body>
    <header>
        {% include 'products/navlinks.html' %}
    </header>
{% endblock pattern_div %}

{% block content %}
<main>
    <div class="stripes">
        <img src="{% static 'images/landingpage-images/long.svg' %}" alt="stripes">
        <img src="{% static 'images/landingpage-images/medium.svg' %}" alt="stripes">
        <img src="{% static 'images/landingpage-images/short.svg' %}" alt="stripes">
    </div>

    <div class="text">
        <h1>Compare the
            <span class="bold">best</span>
            products
            <br>
            at prices you
            <span class="bold">love.</span>
        </h1>
        <br>
        <p>A price comparison website for top brands <br>
            across Amazon and E-Bay.</p>
    </div>

    <div class="button">
        <a href="{% url 'products:product_list' %}">
            <button class="start">Get Started</button>
        </a>
    </div>

    <div class="items">
        {% with list=product_list|slice:":5" %}
        <div class="container">
            {% for product in list %}
            <div class="box">
                <a href="{% url 'products:product_detail' product.id %}">
                    <figure class="caption">
                        <img src="{{ product.image }}" title="{{ product }}"
                             alt="{{ product.product_name|truncatechars_html:18 }}">
                        <figcaption class="caption" title="{{ product }}">
                            {{ product.product_name|truncatechars_html:16 }}
                        </figcaption>
                    </figure>
                </a>
            </div>
            {% endfor %}
            ​
        </div>
        {% endwith %}
        <br/><br/>
        {% with list=product_list|slice:"5:10" %}
        <div class="container">
            {% for product in list %}
            <div class="box">
                <a href="{% url 'products:product_detail' product.id %}">
                    <figure class="caption">
                        <img src="{{ product.image }}" title="{{ product }}"
                             alt="{{ products.product_name|truncatechars_html:18 }}">
                        <figcaption class="caption" title="{{ product }}">
                            {{ product.product_name|truncatechars_html:16 }}
                        </figcaption>
                    </figure>
                </a>
            </div>
            {% endfor %}
            ​
        </div>
        {% endwith %}
    </div>
</main>
<footer>
    <a href="#">PRICEDOUT@2021 </a>
    <a href="#">Terms of Service </a>
    <a href="#">Privacy Policy</a>
    <a href="#">Careers</a>
    <a href="#">Ads Info</a>
    <a href="#">Cookie Policy</a>
</footer>
​
{% endblock content %}

products/templates/products/like_button.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="like_section">
    <h1>Likes: <span id="likes_count">{{ likes.total_likes }}</span></h1>
    <div>
        {% if user.is_authenticated %}
        <a id="{{ likes.id }}"
           style="color: {% if user_like %} orange {% else %} lightgrey {% endif %};"
           class="like_icon">
            <i class="fa fa-star" aria-hidden="true"></i>
        </a>
        {% endif %}
    </div>
    <br/>
    <h1>Comments: {{ product.comments.count }} </h1>
    <a href="{% url 'products:product_modal' product.id %}">
        View comments for this product
    </a>
    <br/>
    <br/>
    <br/>
    <br/>
</div>
{% include 'products/like_button_script.html' %}

products/templates/products/like_button_script.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
// AJAX CALL
$('.like_icon').click(function(){
    $.ajax({
             type: "POST",
             url: "{% url 'products:like' %}",
             data: {'likes_id': $(this).attr('id'),
                    'operation':'like_submit',
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
             },
             dataType: "json",
             success: function(response) {
                selector = document.getElementById(response.likes_id);
                    if(response.user_like==true){
                      $(selector).css("color", "gold");
                    }
                    else if(response.user_like==false){
                      $(selector).css("color", "lightgrey");
                    }
                document.getElementById('likes_count').innerHTML = response.likes_count;
              }
        });
  })
</script>

products/templates/products/navlinks.html
<nav class="navBar">
    <ul class="navLinks">
        <li><a href="{% url 'landing_page' %}">Home</a></li>
        <li><a href="{% url 'about_us' %}">About Us</a></li>
        <li><a href="{% url 'products:product_list' %}">Products</a></li>
        <li><a href="{% url 'faq' %}">FAQS</a></li>
        <li><a href="{% url 'contact_us' %}">Contact Us</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'signup' %}">Login</a></li>
        {% else %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% endif %}
    </ul>
</nav>

products/templates/products/product_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
    <title>PricedOut</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock css %}
</head>
{% block pattern_div %}
<body>

<header>
    <div class="gradient">
    {% include 'products/navlinks.html' %}
    </div>
</header>
{% endblock pattern_div %}
{% if messages %}
<div class="messages" style="text-align: center;">
        {% for message in messages %}
        <p {% if message.tags %} class="{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></p>
        {% endfor %}
</div>
{% endif %}
{% block content %}{% endblock %}

</body>
</html>

products/templates/products/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/item.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static 'images/product_images/logo.png' %}" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/single_product_images/logo.png' %}" type="image/png">

    <title>{{ product }}</title>

    <style>
        .productImage img{
            width: 443px;
            max-height: 607px;
            object-fit: contain;
        }

    </style>
</head>
<body>

<header>
    <div class="headerGradient">
        {% include 'products/navlinks.html' %}
    </div>
</header>
{% if messages %}
<div class="messages" style="text-align: center;">
    {% for message in messages %}
    <p {% if message.tags %} class="{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></p>
    {% endfor %}
</div>
{% endif %}
<div class="centerGrid">
    <div class="container">
        <div class="productImage">
            <img class="item" src="{{ product.image }}">
            <p>Roll over image to zoom in</p>
            <br/>
            {% include 'products/like_button.html' %}
        </div>


        <div class="description">
            <img class="verticalLine" src="{% static 'images/single_product_images/verticalLine.png' %}">
            <div>
                <div class="productName">
                    <h1>{{ product }}</h1>
                </div>

                <p class="store">Sold on Amazon and Ebay</p>

                <div class="features">
                    <h2 class="price">Amazon: ${{ product.amazon_price }}</h2>
                    <h2 class="price">Ebay: ${{ product.ebay_price }}</h2>

                    <ul>
                        {{ list_lines|unordered_list }}
                    </ul>
                </div>

                <img class="horizontalLine" src="{% static 'images/single_product_images/hortizontalLine.png' %}">

                <form class="amazonButton">
                    <button formaction="{{ product.amazon_url }}">Visit Amazon Site</button>
                    <button formaction="{{ product.ebay_url }}">Visit E-bay Site</button>
                </form>
            </div>
        </div>
    </div>
</div>

<footer>
</footer>

</body>
</html>

products/templates/products/product_list.html
{% extends 'products/product_base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/product.css' %}">
<link rel="icon" href="{% static 'images/product_images/logo.png' %}" type="image/svg">
<title>PricedOut | Products</title>
{% endblock css %}
{% block content %}

{% for slice in slices %}
<div class="wrapper">
    <div class=" rowHeaders {% cycle 'table1' 'table2' %}">
        <div class="emptySpace"><p></p></div>
        <h4>Amazon Price</h4>
        <h4>E-bay Price</h4>
        <h4>Category</h4>
    </div>

    {% for product in product_list|slice:slice %}
    <div class="container">
        <div class="productImage {% if user in product.likebutton.user.all %}star{% endif %}">
            <a href="{% url 'products:product_detail' product.pk %}">
                <img class="thumb" src="{{ product.image }}" title="{{ product }}"></a></div>
        <h4 class="productName"><a href="{% url 'products:product_detail' product.pk %}" title="{{ product }}">
            {{ product|wordwrap:25|linebreaksbr|truncatechars_html:20 }}</a></h4>
        <a class="amazonPrice" href="{{ product.amazon_url }}">${{ product.amazon_price }}</a>
        <a class="ebayPrices" href="{{ product.ebay_url}}">${{ product.ebay_price }}</a>
        <h5 class="condition" title="{{ product.category }}">{{ product.category|truncatechars:16 }}</h5>
    </div>
    {% endfor %}
</div>
{% endfor %}

{% endblock content %}